import type { Restaurant, Order, User, DeliveryPartner, Payout } from './types';

export const mockRestaurants: Restaurant[] = [
  {
    id: 'r1',
    name: 'Spice Garden',
    cuisine: 'North Indian • Mughlai',
    rating: 4.5,
    deliveryTime: '25-30 min',
    priceForTwo: 400,
    image: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=400',
    coverImage: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'approved',
    location: 'Koramangala, Bangalore',
    commissionRate: 15,
    ownerName: 'Rajesh Kumar',
    ownerPhone: '+91 90011 22334',
    ownerEmail: 'owner@spicegarden.com',
    businessLicense: 'BL-2023-12345',
    fssaiLicense: 'FSSAI-1234567890',
    walletBalance: 45200,
    address: '123, Main Street, Koramangala, Bangalore',
    operatingHours: '10:00 AM - 10:00 PM',
    menu: [
      {
        id: 'm1',
        name: 'Butter Chicken',
        description: 'Tender chicken in a rich, creamy tomato gravy',
        price: 320,
        image: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Main Course',
        isVeg: false,
        isBestseller: true,
        addons: [
          { name: 'Extra Gravy', price: 40 },
          { name: 'Cheese Topping', price: 60 },
        ],
      },
      {
        id: 'm2',
        name: 'Paneer Tikka Masala',
        description: 'Grilled paneer cubes in spicy tomato-onion gravy',
        price: 280,
        image: 'https://images.pexels.com/photos/4434/food.jpg?auto=compress&cs=tinysrgb&w=400',
        category: 'Main Course',
        isVeg: true,
        isBestseller: true,
        addons: [
          { name: 'Extra Gravy', price: 40 },
          { name: 'Butter Topping', price: 30 },
        ],
      },
      {
        id: 'm3',
        name: 'Garlic Naan',
        description: 'Soft tandoor bread with garlic and butter',
        price: 60,
        image: 'https://images.pexels.com/photos/5337815/pexels-photo-5337815.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Breads',
        isVeg: true,
      },
      {
        id: 'm4',
        name: 'Gulab Jamun (2 pcs)',
        description: 'Deep-fried milk dumplings in sugar syrup',
        price: 120,
        image: 'https://images.pexels.com/photos/6489663/pexels-photo-6489663.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Desserts',
        isVeg: true,
      },
    ],
  },
  {
    id: 'r2',
    name: 'Pizza Central',
    cuisine: 'Italian • Pizza',
    rating: 4.3,
    deliveryTime: '30-35 min',
    priceForTwo: 600,
    image: 'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=400',
    coverImage: 'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'approved',
    location: 'Indiranagar, Bangalore',
    commissionRate: 18,
    ownerName: 'Marco Rossi',
    ownerPhone: '+91 90022 33445',
    ownerEmail: 'owner@pizzacentral.com',
    businessLicense: 'BL-2023-12346',
    fssaiLicense: 'FSSAI-1234567891',
    walletBalance: 38900,
    address: '456, Brigade Road, Indiranagar, Bangalore',
    operatingHours: '11:00 AM - 11:00 PM',
    menu: [
      {
        id: 'm5',
        name: 'Margherita Pizza',
        description: 'Classic pizza with mozzarella, basil & tomato sauce',
        price: 350,
        image: 'https://images.pexels.com/photos/2147496/pexels-photo-2147496.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Pizzas',
        isVeg: true,
        isBestseller: true,
        addons: [
          { name: 'Extra Cheese', price: 80 },
          { name: 'Olives', price: 50 },
          { name: 'Jalapenos', price: 50 },
        ],
      },
      {
        id: 'm6',
        name: 'Pepperoni Pizza',
        description: 'Loaded with pepperoni and mozzarella cheese',
        price: 450,
        image: 'https://images.pexels.com/photos/803975/pexels-photo-803975.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Pizzas',
        isVeg: false,
        isBestseller: true,
        addons: [
          { name: 'Extra Cheese', price: 80 },
          { name: 'Extra Pepperoni', price: 120 },
        ],
      },
      {
        id: 'm7',
        name: 'Garlic Breadsticks',
        description: 'Baked breadsticks with garlic butter and herbs',
        price: 180,
        image: 'https://images.pexels.com/photos/4039573/pexels-photo-4039573.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Sides',
        isVeg: true,
        addons: [
          { name: 'Cheese Dip', price: 60 },
          { name: 'Marinara Dip', price: 40 },
        ],
      },
      {
        id: 'm8',
        name: 'Chocolate Lava Cake',
        description: 'Warm chocolate cake with molten center',
        price: 150,
        image: 'https://images.pexels.com/photos/45202/brownie-dessert-cake-sweet-45202.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Desserts',
        isVeg: true,
      },
    ],
  },
  {
    id: 'r3',
    name: 'Burger Barn',
    cuisine: 'American • Burgers',
    rating: 4.1,
    deliveryTime: '20-25 min',
    priceForTwo: 350,
    image: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=400',
    coverImage: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'approved',
    location: 'HSR Layout, Bangalore',
    commissionRate: 12,
    ownerName: 'John Smith',
    ownerPhone: '+91 90033 44556',
    ownerEmail: 'owner@burgerbarn.com',
    businessLicense: 'BL-2023-12347',
    fssaiLicense: 'FSSAI-1234567892',
    walletBalance: 22300,
    address: '789, 27th Main, HSR Layout, Bangalore',
    operatingHours: '9:00 AM - 11:00 PM',
    menu: [
      {
        id: 'm9',
        name: 'Classic Cheeseburger',
        description: 'Beef patty, cheddar, lettuce, tomato, house sauce',
        price: 220,
        image: 'https://images.pexels.com/photos/1567632/pexels-photo-1567632.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Burgers',
        isVeg: false,
        isBestseller: true,
        addons: [
          { name: 'Extra Patty', price: 80 },
          { name: 'Bacon', price: 60 },
          { name: 'Extra Cheese', price: 40 },
        ],
      },
      {
        id: 'm10',
        name: 'Veggie Delight Burger',
        description: 'Crispy veg patty with fresh veggies and mayo',
        price: 180,
        image: 'https://images.pexels.com/photos/1556909/pexels-photo-1556909.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Burgers',
        isVeg: true,
        addons: [
          { name: 'Extra Cheese', price: 40 },
          { name: 'Fries Combo', price: 90 },
        ],
      },
      {
        id: 'm11',
        name: 'Loaded Fries',
        description: 'Crispy fries with cheese sauce and jalapenos',
        price: 140,
        image: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Sides',
        isVeg: true,
        isBestseller: true,
      },
      {
        id: 'm12',
        name: 'Chocolate Milkshake',
        description: 'Thick chocolate shake with whipped cream',
        price: 160,
        image: 'https://images.pexels.com/photos/3727250/pexels-photo-3727250.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Beverages',
        isVeg: true,
      },
    ],
  },
  {
    id: 'r4',
    name: 'Sushi Republic',
    cuisine: 'Japanese • Sushi',
    rating: 4.7,
    deliveryTime: '35-40 min',
    priceForTwo: 800,
    image: 'https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg?auto=compress&cs=tinysrgb&w=400',
    coverImage: 'https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'approved',
    location: 'Whitefield, Bangalore',
    commissionRate: 20,
    ownerName: 'Kenji Tanaka',
    ownerPhone: '+91 90044 55667',
    ownerEmail: 'owner@sushirepublic.com',
    businessLicense: 'BL-2023-12348',
    fssaiLicense: 'FSSAI-1234567893',
    walletBalance: 15600,
    address: '321, ITPL Road, Whitefield, Bangalore',
    operatingHours: '12:00 PM - 10:00 PM',
    menu: [
      {
        id: 'm13',
        name: 'Salmon Nigiri (4 pcs)',
        description: 'Fresh salmon over seasoned sushi rice',
        price: 420,
        image: 'https://images.pexels.com/photos/895151/pexels-photo-895151.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Nigiri',
        isVeg: false,
        isBestseller: true,
      },
      {
        id: 'm14',
        name: 'California Roll (8 pcs)',
        description: 'Crab, avocado, cucumber wrapped in rice',
        price: 380,
        image: 'https://images.pexels.com/photos/2098085/pexels-photo-2098085.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Rolls',
        isVeg: false,
        isBestseller: true,
        addons: [
          { name: 'Extra Wasabi', price: 20 },
          { name: 'Soy Sauce (Gluten-free)', price: 30 },
        ],
      },
      {
        id: 'm15',
        name: 'Vegetable Tempura',
        description: 'Assorted vegetables in crispy tempura batter',
        price: 300,
        image: 'https://images.pexels.com/photos/6995447/pexels-photo-6995447.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Sides',
        isVeg: true,
      },
      {
        id: 'm16',
        name: 'Mochi Ice Cream',
        description: 'Japanese rice cake with green tea ice cream',
        price: 200,
        image: 'https://images.pexels.com/photos/4193866/pexels-photo-4193866.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Desserts',
        isVeg: true,
      },
    ],
  },
  {
    id: 'r5',
    name: 'Taco Fiesta',
    cuisine: 'Mexican • Tacos',
    rating: 4.2,
    deliveryTime: '25-30 min',
    priceForTwo: 450,
    image: 'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg?auto=compress&cs=tinysrgb&w=400',
    coverImage: 'https://images.pexels.com/photos/2092507/pexels-photo-2092507.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'approved',
    location: 'Jayanagar, Bangalore',
    commissionRate: 14,
    ownerName: 'Maria Garcia',
    ownerPhone: '+91 90055 66778',
    ownerEmail: 'owner@tacofiesta.com',
    businessLicense: 'BL-2023-12349',
    fssaiLicense: 'FSSAI-1234567894',
    walletBalance: 18900,
    address: '654, 4th Block, Jayanagar, Bangalore',
    operatingHours: '11:00 AM - 10:00 PM',
    menu: [
      {
        id: 'm17',
        name: 'Chicken Tacos (3 pcs)',
        description: 'Grilled chicken, salsa, sour cream in soft tortillas',
        price: 260,
        image: 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Tacos',
        isVeg: false,
        isBestseller: true,
        addons: [
          { name: 'Extra Cheese', price: 40 },
          { name: 'Guacamole', price: 60 },
        ],
      },
      {
        id: 'm18',
        name: 'Veg Burrito Bowl',
        description: 'Rice, beans, corn, salsa, cheese and guacamole',
        price: 240,
        image: 'https://images.pexels.com/photos/239975/pexels-photo-239975.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Bowls',
        isVeg: true,
        isBestseller: true,
        addons: [
          { name: 'Double Rice', price: 30 },
          { name: 'Extra Beans', price: 40 },
        ],
      },
      {
        id: 'm19',
        name: 'Nachos Supreme',
        description: 'Tortilla chips loaded with cheese, beans and jalapenos',
        price: 200,
        image: 'https://images.pexels.com/photos/4193883/pexels-photo-4193883.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Sides',
        isVeg: true,
      },
      {
        id: 'm20',
        name: 'Churros with Chocolate',
        description: 'Fried dough sticks with chocolate dipping sauce',
        price: 160,
        image: 'https://images.pexels.com/photos/3727250/pexels-photo-3727250.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Desserts',
        isVeg: true,
      },
    ],
  },
  {
    id: 'r6',
    name: 'Healthy Bowl',
    cuisine: 'Healthy • Salads',
    rating: 4.4,
    deliveryTime: '20-25 min',
    priceForTwo: 500,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400',
    coverImage: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    status: 'approved',
    location: 'MG Road, Bangalore',
    commissionRate: 16,
    ownerName: 'Priya Sharma',
    ownerPhone: '+91 90066 77889',
    ownerEmail: 'owner@healthybowl.com',
    businessLicense: 'BL-2023-12350',
    fssaiLicense: 'FSSAI-1234567895',
    walletBalance: 12400,
    address: '987, MG Road, Bangalore',
    operatingHours: '8:00 AM - 9:00 PM',
    menu: [
      {
        id: 'm21',
        name: 'Grilled Chicken Salad',
        description: 'Mixed greens, grilled chicken, cherry tomatoes, balsamic',
        price: 320,
        image: 'https://images.pexels.com/photos/1213710/pexels-photo-1213710.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Salads',
        isVeg: false,
        isBestseller: true,
        addons: [
          { name: 'Add Avocado', price: 60 },
          { name: 'Extra Chicken', price: 80 },
        ],
      },
      {
        id: 'm22',
        name: 'Quinoa Power Bowl',
        description: 'Quinoa, roasted veggies, chickpeas, tahini dressing',
        price: 290,
        image: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Bowls',
        isVeg: true,
        isBestseller: true,
      },
      {
        id: 'm23',
        name: 'Fresh Fruit Smoothie',
        description: 'Banana, mango, berries blended with almond milk',
        price: 180,
        image: 'https://images.pexels.com/photos/1346154/pexels-photo-1346154.jpeg?auto=compress&cs=tinysrgb&w=400',
        category: 'Beverages',
        isVeg: true,
      },
    ],
  },
];

export const mockOrders: Order[] = [
  {
    id: 'o1',
    orderId: 'FD-2026-001',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 98765 43210',
    deliveryAddress: 'Flat 402, Prestige Apartments, Koramangala, Bangalore 560034',
    restaurantId: 'r1',
    restaurantName: 'Spice Garden',
    items: [
      {
        id: 'ci1',
        menuItem: mockRestaurants[0].menu[0],
        quantity: 2,
        addons: [{ name: 'Extra Gravy', price: 40 }],
        total: 720,
      },
      {
        id: 'ci2',
        menuItem: mockRestaurants[0].menu[2],
        quantity: 4,
        addons: [],
        total: 240,
      },
    ],
    subtotal: 960,
    deliveryFee: 40,
    tax: 48,
    total: 1048,
    status: 'placed',
    placedAt: '2026-09-13T10:30:00Z',
    paymentMethod: 'Paytm UPI',
    paymentStatus: 'paid',
    commissionAmount: 144,
  },
  {
    id: 'o2',
    orderId: 'FD-2026-002',
    customerName: 'Priya Patel',
    customerPhone: '+91 98123 45678',
    deliveryAddress: '12, Brigade Road, Bangalore 560025',
    restaurantId: 'r2',
    restaurantName: 'Pizza Central',
    items: [
      {
        id: 'ci3',
        menuItem: mockRestaurants[1].menu[0],
        quantity: 1,
        addons: [{ name: 'Extra Cheese', price: 80 }],
        total: 430,
      },
      {
        id: 'ci4',
        menuItem: mockRestaurants[1].menu[2],
        quantity: 1,
        addons: [{ name: 'Cheese Dip', price: 60 }],
        total: 240,
      },
    ],
    subtotal: 670,
    deliveryFee: 30,
    tax: 34,
    total: 734,
    status: 'accepted',
    placedAt: '2026-09-13T10:15:00Z',
    acceptedAt: '2026-09-13T10:16:00Z',
    paymentMethod: 'Paytm UPI',
    paymentStatus: 'paid',
    commissionAmount: 121,
  },
  {
    id: 'o3',
    orderId: 'FD-2026-003',
    customerName: 'Arjun Kumar',
    customerPhone: '+91 99887 76655',
    deliveryAddress: '5th Cross, Indiranagar, Bangalore 560038',
    restaurantId: 'r3',
    restaurantName: 'Burger Barn',
    items: [
      {
        id: 'ci5',
        menuItem: mockRestaurants[2].menu[0],
        quantity: 2,
        addons: [{ name: 'Extra Patty', price: 80 }],
        total: 600,
      },
      {
        id: 'ci6',
        menuItem: mockRestaurants[2].menu[2],
        quantity: 1,
        addons: [],
        total: 140,
      },
    ],
    subtotal: 740,
    deliveryFee: 35,
    tax: 37,
    total: 812,
    status: 'ready',
    placedAt: '2026-09-13T10:00:00Z',
    acceptedAt: '2026-09-13T10:01:00Z',
    readyAt: '2026-09-13T10:25:00Z',
    paymentMethod: 'Paytm UPI',
    paymentStatus: 'paid',
    commissionAmount: 89,
  },
  {
    id: 'o4',
    orderId: 'FD-2026-004',
    customerName: 'Sneha Reddy',
    customerPhone: '+91 90080 11223',
    deliveryAddress: 'ITPL Road, Whitefield, Bangalore 560066',
    restaurantId: 'r4',
    restaurantName: 'Sushi Republic',
    items: [
      {
        id: 'ci7',
        menuItem: mockRestaurants[3].menu[0],
        quantity: 2,
        addons: [],
        total: 840,
      },
    ],
    subtotal: 840,
    deliveryFee: 50,
    tax: 42,
    total: 932,
    status: 'picked_up',
    placedAt: '2026-09-13T09:30:00Z',
    acceptedAt: '2026-09-13T09:31:00Z',
    readyAt: '2026-09-13T09:55:00Z',
    pickedUpAt: '2026-09-13T10:05:00Z',
    deliveryPartnerId: 'd2',
    deliveryPartnerName: 'Vikram Singh',
    paymentMethod: 'Paytm UPI',
    paymentStatus: 'paid',
    commissionAmount: 168,
  },
  {
    id: 'o5',
    orderId: 'FD-2026-005',
    customerName: 'Karthik Iyer',
    customerPhone: '+91 91234 56789',
    deliveryAddress: 'Jayanagar 4th Block, Bangalore 560041',
    restaurantId: 'r5',
    restaurantName: 'Taco Fiesta',
    items: [
      {
        id: 'ci8',
        menuItem: mockRestaurants[4].menu[0],
        quantity: 1,
        addons: [{ name: 'Guacamole', price: 60 }],
        total: 320,
      },
      {
        id: 'ci9',
        menuItem: mockRestaurants[4].menu[2],
        quantity: 1,
        addons: [],
        total: 200,
      },
    ],
    subtotal: 520,
    deliveryFee: 30,
    tax: 26,
    total: 576,
    status: 'delivered',
    placedAt: '2026-09-13T08:00:00Z',
    acceptedAt: '2026-09-13T08:01:00Z',
    readyAt: '2026-09-13T08:20:00Z',
    pickedUpAt: '2026-09-13T08:30:00Z',
    deliveredAt: '2026-09-13T08:50:00Z',
    deliveryPartnerId: 'd1',
    deliveryPartnerName: 'Ramesh Yadav',
    paymentMethod: 'Paytm UPI',
    paymentStatus: 'paid',
    commissionAmount: 73,
  },
];

export const mockUsers: User[] = [
  { id: 'u1', name: 'Rahul Sharma', email: 'rahul@email.com', phone: '+91 98765 43210', role: 'customer', status: 'active', joinedAt: '2026-08-15', totalOrders: 3 },
  { id: 'u2', name: 'Priya Patel', email: 'priya@email.com', phone: '+91 98123 45678', role: 'customer', status: 'active', joinedAt: '2026-08-20', totalOrders: 2 },
  { id: 'u3', name: 'Arjun Kumar', email: 'arjun@email.com', phone: '+91 99887 76655', role: 'customer', status: 'active', joinedAt: '2026-09-01', totalOrders: 1 },
  { id: 'u4', name: 'Rajesh Kumar', email: 'owner@spicegarden.com', phone: '+91 90011 22334', role: 'restaurant', status: 'active', joinedAt: '2026-07-10', totalOrders: 52 },
  { id: 'u5', name: 'Maria Garcia', email: 'owner@tacofiesta.com', phone: '+91 90055 66778', role: 'restaurant', status: 'active', joinedAt: '2026-09-10', totalOrders: 28 },
  { id: 'u6', name: 'Ramesh Yadav', email: 'ramesh@delivery.com', phone: '+91 91234 56789', role: 'delivery', status: 'active', joinedAt: '2026-07-15', totalOrders: 342 },
  { id: 'u7', name: 'Vikram Singh', email: 'vikram@delivery.com', phone: '+91 92345 67890', role: 'delivery', status: 'active', joinedAt: '2026-08-01', totalOrders: 298 },
  { id: 'u8', name: 'Admin User', email: 'admin@fooddash.com', phone: '+91 90000 00000', role: 'admin', status: 'active', joinedAt: '2026-06-01', totalOrders: 0 },
  { id: 'u9', name: 'Marco Rossi', email: 'owner@pizzacentral.com', phone: '+91 90022 33445', role: 'restaurant', status: 'active', joinedAt: '2026-07-15', totalOrders: 41 },
  { id: 'u10', name: 'John Smith', email: 'owner@burgerbarn.com', phone: '+91 90033 44556', role: 'restaurant', status: 'active', joinedAt: '2026-08-01', totalOrders: 19 },
  { id: 'u11', name: 'Kenji Tanaka', email: 'owner@sushirepublic.com', phone: '+91 90044 55667', role: 'restaurant', status: 'active', joinedAt: '2026-08-15', totalOrders: 12 },
  { id: 'u12', name: 'Priya Sharma', email: 'owner@healthybowl.com', phone: '+91 90066 77889', role: 'restaurant', status: 'active', joinedAt: '2026-09-01', totalOrders: 8 },
  { id: 'u13', name: 'Suresh Kumar', email: 'suresh@delivery.com', phone: '+91 93456 78901', role: 'delivery', status: 'active', joinedAt: '2026-08-20', totalOrders: 156 },
];

export const mockDeliveryPartners: DeliveryPartner[] = [
  { id: 'd1', name: 'Ramesh Yadav', phone: '+91 91234 56789', email: 'ramesh@delivery.com', status: 'available', totalDeliveries: 342, rating: 4.8, earnings: 28500, vehicleType: 'Bike', joinedAt: '2026-07-15', walletBalance: 28500, licenseNumber: 'DL-2023-45678' },
  { id: 'd2', name: 'Vikram Singh', phone: '+91 92345 67890', email: 'vikram@delivery.com', status: 'on_delivery', totalDeliveries: 298, rating: 4.6, earnings: 24300, vehicleType: 'Bike', joinedAt: '2026-08-01', walletBalance: 24300, licenseNumber: 'DL-2023-45679' },
  { id: 'd3', name: 'Suresh Kumar', phone: '+91 93456 78901', email: 'suresh@delivery.com', status: 'offline', totalDeliveries: 156, rating: 4.4, earnings: 12700, vehicleType: 'Scooter', joinedAt: '2026-08-20', walletBalance: 12700, licenseNumber: 'DL-2023-45680' },
];

export const mockPayouts: Payout[] = [
  { id: 'p1', type: 'restaurant', partnerName: 'Spice Garden', partnerId: 'r1', amount: 45200, commission: 6780, status: 'paid', date: '2026-09-10', orders: 52, paidAt: '2026-09-10T15:30:00Z' },
  { id: 'p2', type: 'restaurant', partnerName: 'Pizza Central', partnerId: 'r2', amount: 38900, commission: 7002, status: 'processed', date: '2026-09-12', orders: 41, processedAt: '2026-09-12T10:00:00Z' },
  { id: 'p3', type: 'delivery', partnerName: 'Ramesh Yadav', partnerId: 'd1', amount: 8500, commission: 0, status: 'paid', date: '2026-09-10', orders: 28, paidAt: '2026-09-10T16:00:00Z' },
  { id: 'p4', type: 'restaurant', partnerName: 'Burger Barn', partnerId: 'r3', amount: 22300, commission: 2676, status: 'pending', date: '2026-09-13', orders: 19 },
  { id: 'p5', type: 'delivery', partnerName: 'Vikram Singh', partnerId: 'd2', amount: 7200, commission: 0, status: 'processed', date: '2026-09-12', orders: 24, processedAt: '2026-09-12T11:30:00Z' },
  { id: 'p6', type: 'restaurant', partnerName: 'Sushi Republic', partnerId: 'r4', amount: 15600, commission: 3120, status: 'failed', date: '2026-09-13', orders: 12, failureReason: 'Bank account verification failed' },
];

export const orderStatusFlow: { status: string; label: string; description: string }[] = [
  { status: 'placed', label: 'Order Placed', description: 'Your order has been received' },
  { status: 'accepted', label: 'Order Confirmed', description: 'Restaurant accepted your order' },
  { status: 'preparing', label: 'Preparing Food', description: 'The chef is cooking your food' },
  { status: 'ready', label: 'Food Ready', description: 'Order is ready for pickup' },
  { status: 'picked_up', label: 'Picked Up', description: 'Delivery partner picked up your order' },
  { status: 'delivered', label: 'Delivered', description: 'Order delivered successfully' },
];
